# Docker images provided by https://github.com/cypress-io/cypress-docker-images
cypress-e2e:
  image: cypress/base:10
  script:
    - npm ci
    - $(npm bin)/cypress verify
    - $(npm bin)/cypress run --record --key 92a66a43-e49f-4951-aa57-48c3682f5e79
  artifacts:
    expire_in: 1 week
    when: always
    paths:
    - cypress/screenshots
    - cypress/videos
